/**
 * Runs pending SQL migrations using the elevated migration role
 * (DATABASE_MIGRATION_URL), never the restricted runtime role
 * (DATABASE_URL) that the rest of the app uses — see client.ts and
 * docs/security.md.
 *
 * Migrations themselves are hand-reviewed SQL files under
 * packages/database/migrations/, generated by `pnpm --filter
 * @uptet/database generate` from the schema in src/schema/. Never hand-edit
 * a migration file that has already been applied anywhere (including a
 * teammate's machine) — add a new migration instead.
 */
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import dotenv from "dotenv";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../../../.env") });

async function main() {
  const connectionString = process.env.DATABASE_MIGRATION_URL;
  if (!connectionString) {
    throw new Error(
      "DATABASE_MIGRATION_URL is not set. This must be a more privileged role than DATABASE_URL — see docs/security.md.",
    );
  }

  const migrationClient = postgres(connectionString, { max: 1 });
  const db = drizzle(migrationClient);

  console.log("Running migrations...");
  await migrate(db, { migrationsFolder: "./migrations" });
  console.log("Migrations complete.");

  await migrationClient.end();
}

main().catch((error) => {
  console.error("Migration failed:", error);
  process.exit(1);
});
